apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: machine-approver
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec: {}
status:
  relatedObjects:
  - group: ""
    name: openshift-cluster-machine-approver
    resource: namespaces
  - group: certificates.k8s.io
    name: ""
    resource: certificatesigningrequests
  - group: rbac.authorization.k8s.io
    name: system:openshift:controller:machine-approver
    resource: clusterroles
  versions:
    - name: operator
      version: "0.0.1-snapshot"
